import { AuthState } from '../models/auth.models';
import {
  createInitialAuthState,
  LS_ACCESS_TOKEN_KEY,
  LS_BANK_CONNECTION_STATE_KEY,
  LS_HAS_CONNECTED_BANK_KEY,
  LS_ONBOARDING_COMPLETED_KEY,
  LS_ONBOARDING_CURRENT_STEP_KEY,
  LS_PENDING_CONSENT_STATE_KEY,
  LS_PENDING_GOOGLE_STATE_KEY,
} from './auth-storage';

export {
  LS_ACCESS_TOKEN_KEY,
  LS_BANK_CONNECTION_STATE_KEY,
  LS_HAS_CONNECTED_BANK_KEY,
  LS_ONBOARDING_COMPLETED_KEY,
  LS_ONBOARDING_CURRENT_STEP_KEY,
  LS_PENDING_CONSENT_STATE_KEY,
  LS_PENDING_GOOGLE_STATE_KEY,
};

export const initialAuthState: AuthState = createInitialAuthState();
