import { RulesState } from '../models/rules.models';

export const initialRulesState: RulesState = {
  description: 'Rules define how your financial system operates.',
  quickTemplatesTitle: 'QUICK TEMPLATES',
  quickTemplates: [
    {
      id: 'auto-classification',
      title: 'Auto-classification',
      subtitle: 'Merchant-based automation',
    },
    {
      id: 'threshold-control',
      title: 'Threshold control',
      subtitle: '75% \u00b7 90% \u00b7 100%',
    },
    {
      id: 'anomaly-detection',
      title: 'Anomaly detection',
      subtitle: 'Unusual spending patterns',
    },
  ],
  activeTitle: 'ACTIVE RULES',
  activeSummary: '5 active \u00b7 4 triggers this month',
  addLabel: 'Add',
  activeRules: [
    {
      id: 'rule-uber-auto',
      icon: 'tag',
      title: 'Auto-categorize Uber',
      tone: 'auto',
      statusLabel: 'AUTO',
      condition: 'Condition: merchant contains "Uber"',
      activity: 'Applied to 14 transactions this month',
      enabled: true,
    },
    {
      id: 'rule-grocery-75',
      icon: 'bell',
      title: 'Grocery alert at 75%',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: groceries reach 75%',
      activity: 'Triggered 3 times this month',
      enabled: true,
    },
    {
      id: 'rule-shopping-90',
      icon: 'bell',
      title: 'Shopping alert at 90%',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: shopping reaches 90%',
      activity: 'Triggered 1 time this month',
      enabled: true,
    },
    {
      id: 'rule-netflix-auto',
      icon: 'tag',
      title: 'Auto-categorize Netflix',
      tone: 'auto',
      statusLabel: 'AUTO',
      condition: 'Condition: merchant contains "Netflix"',
      activity: 'Applied to 8 transactions this month',
      enabled: true,
    },
    {
      id: 'rule-unusual-spending',
      icon: 'warning',
      title: 'Unusual spending detection',
      tone: 'anomaly',
      statusLabel: 'ANOMALY',
      condition: 'Condition: any category exceeds 150%...',
      activity: 'No triggers yet',
      enabled: false,
      stateLabel: 'Disabled',
    },
    {
      id: 'rule-large-purchase',
      icon: 'bell',
      title: 'Large purchase alert',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: amount > $200',
      activity: 'Triggered 2 times this month',
      enabled: true,
    },
  ],
  triggeredTitle: 'TRIGGERED ALERTS',
  triggeredSummary: 'Latest trigger: 2h ago \u00b7 4 this month',
  triggeredAlerts: [
    {
      id: 'alert-shopping-90',
      title: 'Shopping reached 90% threshold',
      severity: 'warning',
      severityLabel: 'WARNING',
      ageLabel: '2h ago',
    },
    {
      id: 'alert-home-100',
      title: 'Home budget exceeded 100%',
      severity: 'critical',
      severityLabel: 'CRITICAL',
      ageLabel: '24d ago',
    },
    {
      id: 'alert-gym-100',
      title: 'Gym budget exceeded 100%',
      severity: 'critical',
      severityLabel: 'CRITICAL',
      ageLabel: '3d ago',
    },
    {
      id: 'alert-groceries-75',
      title: 'Groceries approaching 75% alert',
      severity: 'warning',
      severityLabel: 'WARNING',
      ageLabel: '1d ago',
    },
  ],
  isAddRuleModalOpen: false,
  addDraft: {
    ruleName: '',
    ruleType: 'Auto-classification',
    conditionField: 'merchant contains',
    conditionValue: '',
    actionType: 'set category to',
    actionValue: 'Category',
  },
  ruleTypeOptions: ['Auto-classification', 'Threshold alert', 'Anomaly detection'],
  conditionFieldOptions: ['merchant contains', 'amount greater than', 'category reaches'],
  actionTypeOptions: ['set category to', 'send notification', 'flag as anomaly'],
  actionValueOptions: ['Category', 'Baby', 'Groceries', 'Home', 'Transport', 'Gym'],
};
