import { RulesState } from '../models/rules.models';

export const initialRulesState: RulesState = {
  description: 'Rules define how your financial system operates.',
  quickTemplatesTitle: 'Quick create',
  quickTemplates: [
    {
      id: 'auto-classification',
      title: 'Auto-tag',
      subtitle: 'Merchant-based automation',
    },
    {
      id: 'threshold-alert',
      title: 'Alert',
      subtitle: 'Threshold notifications',
    },
    {
      id: 'anomaly-detection',
      title: 'Anomaly',
      subtitle: 'Unusual spending detection',
    },
  ],
  activeTitle: 'Your rules',
  activeSummary: '5 of 6 rules running',
  addLabel: 'New',
  activeRules: [
    {
      id: 'rule-uber-auto',
      icon: 'tag',
      title: 'Auto-categorize Uber',
      tone: 'auto',
      statusLabel: 'AUTO',
      condition: 'Condition: merchant contains "Uber"',
      activity: '11 tagged this month',
      enabled: true,
    },
    {
      id: 'rule-grocery-75',
      icon: 'bell',
      title: 'Grocery alert at 75%',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: groceries reaches 75%',
      activity: '1 triggers this month',
      enabled: true,
    },
    {
      id: 'rule-shopping-90',
      icon: 'bell',
      title: 'Shopping alert at 90%',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: shopping reaches 90%',
      activity: '0 triggers this month',
      enabled: true,
    },
    {
      id: 'rule-netflix-auto',
      icon: 'tag',
      title: 'Auto-categorize Netflix',
      tone: 'auto',
      statusLabel: 'AUTO',
      condition: 'Condition: merchant contains "Netflix"',
      activity: '17 tagged this month',
      enabled: true,
    },
    {
      id: 'rule-unusual-spending',
      icon: 'warning',
      title: 'Unusual spending detection',
      tone: 'anomaly',
      statusLabel: 'ANOMALY',
      condition: 'Condition: spending exceeds 150% of average',
      activity: 'Paused',
      enabled: false,
      stateLabel: 'Paused',
    },
    {
      id: 'rule-large-purchase',
      icon: 'bell',
      title: 'Large purchase alert',
      tone: 'alert',
      statusLabel: 'ALERT',
      condition: 'Condition: single transaction over $200',
      activity: '3 triggers this month',
      enabled: true,
    },
  ],
  triggeredTitle: 'Recent activity',
  triggeredSummary: 'Last 7 days',
  triggeredAlerts: [
    {
      id: 'activity-uber-transport',
      title: 'Auto-tagged 3 Uber rides to Transport',
      icon: 'tag',
      ageLabel: '2h ago',
    },
    {
      id: 'activity-shopping-threshold',
      title: 'Shopping reached 90% threshold',
      icon: 'bell',
      ageLabel: '1d ago',
    },
    {
      id: 'activity-netflix-entertainment',
      title: 'Auto-tagged Netflix to Entertainment',
      icon: 'tag',
      ageLabel: '2d ago',
    },
  ],
  isAddRuleModalOpen: false,
  addDraft: {
    ruleName: '',
    ruleType: 'Auto-classification',
    conditionField: 'merchant contains',
    conditionValue: '',
    actionType: 'set category to',
    actionValue: 'Baby',
  },
  ruleTypeOptions: ['Auto-classification', 'Threshold alert', 'Anomaly detection'],
  conditionFieldOptions: ['merchant contains', 'category reaches', 'spending exceeds'],
  actionTypeOptions: ['set category to', 'send notification', 'flag as anomaly'],
  actionValueOptions: ['Baby', 'Groceries', 'Home', 'Transport', 'Gym', 'Shopping', 'Entertainment'],
};
