import { BudgetState } from '../models/budget.models';

export const initialBudgetState: BudgetState = {
  overviewTitle: 'MONTHLY OVERVIEW',
  overviewMetrics: [
    { id: 'planned', label: 'Planned', value: '$3,920' },
    { id: 'spent', label: 'Spent', value: '$3,246' },
    { id: 'remaining', label: 'Remaining', value: '$674' },
  ],
  signals: [
    { id: 'on-track', count: 2, label: 'On Track', tone: 'on-track' },
    { id: 'watch', count: 4, label: 'Watch', tone: 'watch' },
    { id: 'over', count: 2, label: 'Over', tone: 'over' },
  ],
  categoryTitle: 'CATEGORY BUDGETS',
  editBudgetsLabel: '+ Edit budgets',
  categories: [
    {
      id: 'baby',
      name: 'Baby',
      spentLabel: '$312',
      limitLabel: '$400',
      leftLabel: '$88 left',
      noteLabel: 'Safe pace',
      status: 'watch',
      progressPercent: 78,
      iconName: 'happy-outline',
      iconTone: 'baby',
    },
    {
      id: 'groceries',
      name: 'Groceries',
      spentLabel: '$624',
      limitLabel: '$800',
      leftLabel: '$176 left',
      noteLabel: 'Safe pace',
      status: 'watch',
      progressPercent: 78,
      iconName: 'cart-outline',
      iconTone: 'groceries',
    },
    {
      id: 'home',
      name: 'Home',
      spentLabel: '$1,200',
      limitLabel: '$1,200',
      leftLabel: '$0 left',
      noteLabel: 'Exceeded',
      status: 'over',
      progressPercent: 100,
      iconName: 'home-outline',
      iconTone: 'home',
    },
    {
      id: 'transport',
      name: 'Transport',
      spentLabel: '$289',
      limitLabel: '$350',
      leftLabel: '$61 left',
      noteLabel: 'Safe pace',
      status: 'watch',
      progressPercent: 83,
      iconName: 'car-sport-outline',
      iconTone: 'transport',
    },
    {
      id: 'gym',
      name: 'Gym',
      spentLabel: '$120',
      limitLabel: '$120',
      leftLabel: '$0 left',
      noteLabel: 'Exceeded',
      status: 'over',
      progressPercent: 100,
      iconName: 'barbell-outline',
      iconTone: 'gym',
    },
    {
      id: 'shopping',
      name: 'Shopping',
      spentLabel: '$467',
      limitLabel: '$500',
      leftLabel: '$33 left',
      noteLabel: 'Exceeds ~day 27',
      status: 'watch',
      progressPercent: 93,
      iconName: 'bag-handle-outline',
      iconTone: 'shopping',
    },
    {
      id: 'entertainment',
      name: 'Entertainment',
      spentLabel: '$145',
      limitLabel: '$300',
      leftLabel: '$155 left',
      noteLabel: 'Safe pace',
      status: 'on-track',
      progressPercent: 48,
      iconName: 'business-outline',
      iconTone: 'entertainment',
    },
    {
      id: 'health',
      name: 'Health',
      spentLabel: '$89',
      limitLabel: '$250',
      leftLabel: '$161 left',
      noteLabel: 'Safe pace',
      status: 'on-track',
      progressPercent: 36,
      iconName: 'heart-outline',
      iconTone: 'health',
    },
  ],
  editRequests: 0,
  lastOpenedItemId: null,
  isNewBudgetModalOpen: false,
  newBudgetNameInput: '',
  newBudgetAmountInput: '',
};
